[2024-06-12T17:36:12.594+0000] {local_task_job_runner.py:120} INFO - ::group::Pre task execution logs
[2024-06-12T17:36:12.617+0000] {taskinstance.py:2073} INFO - Dependencies all met for dep_context=non-requeueable deps ti=<TaskInstance: parsing_wb_mpstats.parsing_wb manual__2024-06-12T17:35:59.176748+00:00 [queued]>
[2024-06-12T17:36:12.625+0000] {taskinstance.py:2073} INFO - Dependencies all met for dep_context=requeueable deps ti=<TaskInstance: parsing_wb_mpstats.parsing_wb manual__2024-06-12T17:35:59.176748+00:00 [queued]>
[2024-06-12T17:36:12.625+0000] {taskinstance.py:2303} INFO - Starting attempt 1 of 4
[2024-06-12T17:36:12.636+0000] {taskinstance.py:2327} INFO - Executing <Task(PythonOperator): parsing_wb> on 2024-06-12 17:35:59.176748+00:00
[2024-06-12T17:36:12.644+0000] {warnings.py:110} WARNING - /home/***/.local/lib/python3.12/site-packages/***/task/task_runner/standard_task_runner.py:61: DeprecationWarning: This process (pid=66) is multi-threaded, use of fork() may lead to deadlocks in the child.
  pid = os.fork()

[2024-06-12T17:36:12.645+0000] {standard_task_runner.py:63} INFO - Started process 68 to run task
[2024-06-12T17:36:12.646+0000] {standard_task_runner.py:90} INFO - Running: ['***', 'tasks', 'run', 'parsing_wb_mpstats', 'parsing_wb', 'manual__2024-06-12T17:35:59.176748+00:00', '--job-id', '1419', '--raw', '--subdir', 'DAGS_FOLDER/parsing_wb_mpstats/parsing.py', '--cfg-path', '/tmp/tmpvwwep6el']
[2024-06-12T17:36:12.647+0000] {standard_task_runner.py:91} INFO - Job 1419: Subtask parsing_wb
[2024-06-12T17:36:12.701+0000] {task_command.py:426} INFO - Running <TaskInstance: parsing_wb_mpstats.parsing_wb manual__2024-06-12T17:35:59.176748+00:00 [running]> on host d40bdb4a74ef
[2024-06-12T17:36:12.800+0000] {taskinstance.py:2644} INFO - Exporting env vars: AIRFLOW_CTX_DAG_OWNER='***' AIRFLOW_CTX_DAG_ID='parsing_wb_mpstats' AIRFLOW_CTX_TASK_ID='parsing_wb' AIRFLOW_CTX_EXECUTION_DATE='2024-06-12T17:35:59.176748+00:00' AIRFLOW_CTX_TRY_NUMBER='1' AIRFLOW_CTX_DAG_RUN_ID='manual__2024-06-12T17:35:59.176748+00:00'
[2024-06-12T17:36:12.802+0000] {taskinstance.py:430} INFO - ::endgroup::
[2024-06-12T17:36:30.529+0000] {connection_workflow.py:179} INFO - Pika version 1.3.2 connecting to ('172.21.0.2', 5672)
[2024-06-12T17:36:30.530+0000] {io_services_utils.py:345} INFO - Socket connected: <socket.socket fd=98, family=2, type=1, proto=6, laddr=('172.21.0.5', 60704), raddr=('172.21.0.2', 5672)>
[2024-06-12T17:36:30.532+0000] {connection_workflow.py:428} INFO - Streaming transport linked up: (<pika.adapters.utils.io_services_utils._AsyncPlaintextTransport object at 0x7fc721cd1130>, _StreamingProtocolShim: <SelectConnection PROTOCOL transport=<pika.adapters.utils.io_services_utils._AsyncPlaintextTransport object at 0x7fc721cd1130> params=<ConnectionParameters host=rabbitmq port=5672 virtual_host=/ ssl=False>>).
[2024-06-12T17:36:30.537+0000] {connection_workflow.py:293} INFO - AMQPConnector - reporting success: <SelectConnection OPEN transport=<pika.adapters.utils.io_services_utils._AsyncPlaintextTransport object at 0x7fc721cd1130> params=<ConnectionParameters host=rabbitmq port=5672 virtual_host=/ ssl=False>>
[2024-06-12T17:36:30.537+0000] {connection_workflow.py:725} INFO - AMQPConnectionWorkflow - reporting success: <SelectConnection OPEN transport=<pika.adapters.utils.io_services_utils._AsyncPlaintextTransport object at 0x7fc721cd1130> params=<ConnectionParameters host=rabbitmq port=5672 virtual_host=/ ssl=False>>
[2024-06-12T17:36:30.538+0000] {blocking_connection.py:453} INFO - Connection workflow succeeded: <SelectConnection OPEN transport=<pika.adapters.utils.io_services_utils._AsyncPlaintextTransport object at 0x7fc721cd1130> params=<ConnectionParameters host=rabbitmq port=5672 virtual_host=/ ssl=False>>
[2024-06-12T17:36:30.538+0000] {blocking_connection.py:1264} INFO - Created channel=1
[2024-06-12T17:36:30.539+0000] {blocking_connection.py:802} INFO - Closing connection (200): Normal shutdown
[2024-06-12T17:36:30.540+0000] {channel.py:536} INFO - Closing channel (200): 'Normal shutdown' on <Channel number=1 OPEN conn=<SelectConnection OPEN transport=<pika.adapters.utils.io_services_utils._AsyncPlaintextTransport object at 0x7fc721cd1130> params=<ConnectionParameters host=rabbitmq port=5672 virtual_host=/ ssl=False>>>
[2024-06-12T17:36:30.540+0000] {channel.py:1133} INFO - Received <Channel.CloseOk> on <Channel number=1 CLOSING conn=<SelectConnection OPEN transport=<pika.adapters.utils.io_services_utils._AsyncPlaintextTransport object at 0x7fc721cd1130> params=<ConnectionParameters host=rabbitmq port=5672 virtual_host=/ ssl=False>>>
[2024-06-12T17:36:30.541+0000] {connection.py:1316} INFO - Closing connection (200): 'Normal shutdown'
[2024-06-12T17:36:30.541+0000] {io_services_utils.py:731} INFO - Aborting transport connection: state=1; <socket.socket fd=98, family=2, type=1, proto=6, laddr=('172.21.0.5', 60704), raddr=('172.21.0.2', 5672)>
[2024-06-12T17:36:30.542+0000] {io_services_utils.py:904} INFO - _AsyncTransportBase._initate_abort(): Initiating abrupt asynchronous transport shutdown: state=1; error=None; <socket.socket fd=98, family=2, type=1, proto=6, laddr=('172.21.0.5', 60704), raddr=('172.21.0.2', 5672)>
[2024-06-12T17:36:30.542+0000] {io_services_utils.py:869} INFO - Deactivating transport: state=1; <socket.socket fd=98, family=2, type=1, proto=6, laddr=('172.21.0.5', 60704), raddr=('172.21.0.2', 5672)>
[2024-06-12T17:36:30.542+0000] {connection.py:2017} INFO - AMQP stack terminated, failed to connect, or aborted: opened=True, error-arg=None; pending-error=ConnectionClosedByClient: (200) 'Normal shutdown'
[2024-06-12T17:36:30.542+0000] {connection.py:2086} INFO - Stack terminated due to ConnectionClosedByClient: (200) 'Normal shutdown'
[2024-06-12T17:36:30.543+0000] {io_services_utils.py:882} INFO - Closing transport socket and unlinking: state=3; <socket.socket fd=98, family=2, type=1, proto=6, laddr=('172.21.0.5', 60704), raddr=('172.21.0.2', 5672)>
[2024-06-12T17:36:30.543+0000] {blocking_connection.py:525} INFO - User-initiated close: result=(<SelectConnection CLOSED transport=None params=<ConnectionParameters host=rabbitmq port=5672 virtual_host=/ ssl=False>>, ConnectionClosedByClient: (200) 'Normal shutdown')
[2024-06-12T17:36:30.543+0000] {taskinstance.py:441} INFO - ::group::Post task execution logs
[2024-06-12T17:36:30.544+0000] {taskinstance.py:2890} ERROR - Task failed with exception
Traceback (most recent call last):
  File "/opt/airflow/dags/parsing_wb_mpstats/parsing_wb.py", line 336, in main
    data_all_nmids_current, data_all_nmids_previous = get_data_from_wb(nmids)
                                                      ^^^^^^^^^^^^^^^^^^^^^^^
  File "/opt/airflow/dags/parsing_wb_mpstats/parsing_wb.py", line 315, in get_data_from_wb
    data_all_nmids_previous = get_detail_history_report(nmids_list, df_p, dt_p)
                              ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/opt/airflow/dags/parsing_wb_mpstats/parsing_wb.py", line 265, in get_detail_history_report
    if response['error']:
       ~~~~~~~~^^^^^^^^^
TypeError: 'Response' object is not subscriptable

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/taskinstance.py", line 465, in _execute_task
    result = _execute_callable(context=context, **execute_callable_kwargs)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/taskinstance.py", line 432, in _execute_callable
    return execute_callable(context=context, **execute_callable_kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/baseoperator.py", line 400, in wrapper
    return func(self, *args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/operators/python.py", line 235, in execute
    return_value = self.execute_callable()
                   ^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/operators/python.py", line 252, in execute_callable
    return self.python_callable(*self.op_args, **self.op_kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/opt/airflow/dags/parsing_wb_mpstats/parsing.py", line 36, in get_nmids_and_run_parsing_wb
    return main_wb(nmids=result['nmids'])
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/opt/airflow/dags/parsing_wb_mpstats/parsing_wb.py", line 343, in main
    raise Exception
Exception
[2024-06-12T17:36:30.560+0000] {taskinstance.py:1205} INFO - Marking task as UP_FOR_RETRY. dag_id=parsing_wb_mpstats, task_id=parsing_wb, execution_date=20240612T173559, start_date=20240612T173612, end_date=20240612T173630
[2024-06-12T17:36:30.576+0000] {standard_task_runner.py:110} ERROR - Failed to execute job 1419 for task parsing_wb (; 68)
[2024-06-12T17:36:30.598+0000] {local_task_job_runner.py:240} INFO - Task exited with return code 1
[2024-06-12T17:36:30.617+0000] {taskinstance.py:3482} INFO - 0 downstream tasks scheduled from follow-on schedule check
[2024-06-12T17:36:30.619+0000] {local_task_job_runner.py:222} INFO - ::endgroup::
