[2024-07-05T06:07:33.138+0000] {local_task_job_runner.py:120} INFO - ::group::Pre task execution logs
[2024-07-05T06:07:33.228+0000] {taskinstance.py:2073} INFO - Dependencies all met for dep_context=non-requeueable deps ti=<TaskInstance: parsing_wb_mpstats.parsing_wb scheduled__2024-07-04T06:00:00+00:00 [queued]>
[2024-07-05T06:07:33.261+0000] {taskinstance.py:2073} INFO - Dependencies all met for dep_context=requeueable deps ti=<TaskInstance: parsing_wb_mpstats.parsing_wb scheduled__2024-07-04T06:00:00+00:00 [queued]>
[2024-07-05T06:07:33.262+0000] {taskinstance.py:2303} INFO - Starting attempt 4 of 4
[2024-07-05T06:07:33.320+0000] {taskinstance.py:2327} INFO - Executing <Task(PythonOperator): parsing_wb> on 2024-07-04 06:00:00+00:00
[2024-07-05T06:07:33.352+0000] {warnings.py:110} WARNING - /home/***/.local/lib/python3.12/site-packages/***/task/task_runner/standard_task_runner.py:61: DeprecationWarning: This process (pid=423964) is multi-threaded, use of fork() may lead to deadlocks in the child.
  pid = os.fork()

[2024-07-05T06:07:33.356+0000] {standard_task_runner.py:63} INFO - Started process 423966 to run task
[2024-07-05T06:07:33.358+0000] {standard_task_runner.py:90} INFO - Running: ['***', 'tasks', 'run', 'parsing_wb_mpstats', 'parsing_wb', 'scheduled__2024-07-04T06:00:00+00:00', '--job-id', '2123', '--raw', '--subdir', 'DAGS_FOLDER/parsing_wb_mpstats/parsing.py', '--cfg-path', '/tmp/tmpvu1xmuij']
[2024-07-05T06:07:33.361+0000] {standard_task_runner.py:91} INFO - Job 2123: Subtask parsing_wb
[2024-07-05T06:07:33.562+0000] {task_command.py:426} INFO - Running <TaskInstance: parsing_wb_mpstats.parsing_wb scheduled__2024-07-04T06:00:00+00:00 [running]> on host d40bdb4a74ef
[2024-07-05T06:07:33.909+0000] {taskinstance.py:2644} INFO - Exporting env vars: AIRFLOW_CTX_DAG_OWNER='***' AIRFLOW_CTX_DAG_ID='parsing_wb_mpstats' AIRFLOW_CTX_TASK_ID='parsing_wb' AIRFLOW_CTX_EXECUTION_DATE='2024-07-04T06:00:00+00:00' AIRFLOW_CTX_TRY_NUMBER='4' AIRFLOW_CTX_DAG_RUN_ID='scheduled__2024-07-04T06:00:00+00:00'
[2024-07-05T06:07:33.916+0000] {taskinstance.py:430} INFO - ::endgroup::
[2024-07-05T06:08:41.110+0000] {connection_workflow.py:179} INFO - Pika version 1.3.2 connecting to ('172.21.0.2', 5672)
[2024-07-05T06:08:41.112+0000] {io_services_utils.py:345} INFO - Socket connected: <socket.socket fd=98, family=2, type=1, proto=6, laddr=('172.21.0.5', 45354), raddr=('172.21.0.2', 5672)>
[2024-07-05T06:08:41.115+0000] {connection_workflow.py:428} INFO - Streaming transport linked up: (<pika.adapters.utils.io_services_utils._AsyncPlaintextTransport object at 0x7fc721cd91c0>, _StreamingProtocolShim: <SelectConnection PROTOCOL transport=<pika.adapters.utils.io_services_utils._AsyncPlaintextTransport object at 0x7fc721cd91c0> params=<ConnectionParameters host=rabbitmq port=5672 virtual_host=/ ssl=False>>).
[2024-07-05T06:08:41.121+0000] {connection_workflow.py:293} INFO - AMQPConnector - reporting success: <SelectConnection OPEN transport=<pika.adapters.utils.io_services_utils._AsyncPlaintextTransport object at 0x7fc721cd91c0> params=<ConnectionParameters host=rabbitmq port=5672 virtual_host=/ ssl=False>>
[2024-07-05T06:08:41.122+0000] {connection_workflow.py:725} INFO - AMQPConnectionWorkflow - reporting success: <SelectConnection OPEN transport=<pika.adapters.utils.io_services_utils._AsyncPlaintextTransport object at 0x7fc721cd91c0> params=<ConnectionParameters host=rabbitmq port=5672 virtual_host=/ ssl=False>>
[2024-07-05T06:08:41.122+0000] {blocking_connection.py:453} INFO - Connection workflow succeeded: <SelectConnection OPEN transport=<pika.adapters.utils.io_services_utils._AsyncPlaintextTransport object at 0x7fc721cd91c0> params=<ConnectionParameters host=rabbitmq port=5672 virtual_host=/ ssl=False>>
[2024-07-05T06:08:41.123+0000] {blocking_connection.py:1264} INFO - Created channel=1
[2024-07-05T06:08:41.125+0000] {blocking_connection.py:802} INFO - Closing connection (200): Normal shutdown
[2024-07-05T06:08:41.125+0000] {channel.py:536} INFO - Closing channel (200): 'Normal shutdown' on <Channel number=1 OPEN conn=<SelectConnection OPEN transport=<pika.adapters.utils.io_services_utils._AsyncPlaintextTransport object at 0x7fc721cd91c0> params=<ConnectionParameters host=rabbitmq port=5672 virtual_host=/ ssl=False>>>
[2024-07-05T06:08:41.130+0000] {channel.py:1133} INFO - Received <Channel.CloseOk> on <Channel number=1 CLOSING conn=<SelectConnection OPEN transport=<pika.adapters.utils.io_services_utils._AsyncPlaintextTransport object at 0x7fc721cd91c0> params=<ConnectionParameters host=rabbitmq port=5672 virtual_host=/ ssl=False>>>
[2024-07-05T06:08:41.131+0000] {connection.py:1316} INFO - Closing connection (200): 'Normal shutdown'
[2024-07-05T06:08:41.131+0000] {io_services_utils.py:731} INFO - Aborting transport connection: state=1; <socket.socket fd=98, family=2, type=1, proto=6, laddr=('172.21.0.5', 45354), raddr=('172.21.0.2', 5672)>
[2024-07-05T06:08:41.132+0000] {io_services_utils.py:904} INFO - _AsyncTransportBase._initate_abort(): Initiating abrupt asynchronous transport shutdown: state=1; error=None; <socket.socket fd=98, family=2, type=1, proto=6, laddr=('172.21.0.5', 45354), raddr=('172.21.0.2', 5672)>
[2024-07-05T06:08:41.132+0000] {io_services_utils.py:869} INFO - Deactivating transport: state=1; <socket.socket fd=98, family=2, type=1, proto=6, laddr=('172.21.0.5', 45354), raddr=('172.21.0.2', 5672)>
[2024-07-05T06:08:41.132+0000] {connection.py:2017} INFO - AMQP stack terminated, failed to connect, or aborted: opened=True, error-arg=None; pending-error=ConnectionClosedByClient: (200) 'Normal shutdown'
[2024-07-05T06:08:41.133+0000] {connection.py:2086} INFO - Stack terminated due to ConnectionClosedByClient: (200) 'Normal shutdown'
[2024-07-05T06:08:41.133+0000] {io_services_utils.py:882} INFO - Closing transport socket and unlinking: state=3; <socket.socket fd=98, family=2, type=1, proto=6, laddr=('172.21.0.5', 45354), raddr=('172.21.0.2', 5672)>
[2024-07-05T06:08:41.133+0000] {blocking_connection.py:525} INFO - User-initiated close: result=(<SelectConnection CLOSED transport=None params=<ConnectionParameters host=rabbitmq port=5672 virtual_host=/ ssl=False>>, ConnectionClosedByClient: (200) 'Normal shutdown')
[2024-07-05T06:08:41.134+0000] {taskinstance.py:441} INFO - ::group::Post task execution logs
[2024-07-05T06:08:41.135+0000] {taskinstance.py:2890} ERROR - Task failed with exception
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/requests/models.py", line 971, in json
    return complexjson.loads(self.text, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.12/json/__init__.py", line 346, in loads
    return _default_decoder.decode(s)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.12/json/decoder.py", line 337, in decode
    obj, end = self.raw_decode(s, idx=_w(s, 0).end())
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.12/json/decoder.py", line 355, in raw_decode
    raise JSONDecodeError("Expecting value", s, err.value) from None
json.decoder.JSONDecodeError: Expecting value: line 1 column 1 (char 0)

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/opt/airflow/dags/parsing_wb_mpstats/parsing_wb.py", line 363, in main
    data_all_nmids_current, data_all_nmids_previous = get_data_from_wb(nmids)
                                                      ^^^^^^^^^^^^^^^^^^^^^^^
  File "/opt/airflow/dags/parsing_wb_mpstats/parsing_wb.py", line 337, in get_data_from_wb
    history_for_vendorcode.update(get_history(nmids, df_c, dt_c))
                                  ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/opt/airflow/dags/parsing_wb_mpstats/parsing_wb.py", line 97, in get_history
    rq = response.json()
         ^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/requests/models.py", line 975, in json
    raise RequestsJSONDecodeError(e.msg, e.doc, e.pos)
requests.exceptions.JSONDecodeError: Expecting value: line 1 column 1 (char 0)

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/taskinstance.py", line 465, in _execute_task
    result = _execute_callable(context=context, **execute_callable_kwargs)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/taskinstance.py", line 432, in _execute_callable
    return execute_callable(context=context, **execute_callable_kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/baseoperator.py", line 400, in wrapper
    return func(self, *args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/operators/python.py", line 235, in execute
    return_value = self.execute_callable()
                   ^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/operators/python.py", line 252, in execute_callable
    return self.python_callable(*self.op_args, **self.op_kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/opt/airflow/dags/parsing_wb_mpstats/parsing.py", line 36, in get_nmids_and_run_parsing_wb
    return main_wb(nmids=result['nmids'])
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/opt/airflow/dags/parsing_wb_mpstats/parsing_wb.py", line 372, in main
    raise Exception
Exception
[2024-07-05T06:08:41.157+0000] {taskinstance.py:1205} INFO - Marking task as FAILED. dag_id=parsing_wb_mpstats, task_id=parsing_wb, execution_date=20240704T060000, start_date=20240705T060733, end_date=20240705T060841
[2024-07-05T06:08:41.175+0000] {standard_task_runner.py:110} ERROR - Failed to execute job 2123 for task parsing_wb (; 423966)
[2024-07-05T06:08:41.216+0000] {local_task_job_runner.py:240} INFO - Task exited with return code 1
[2024-07-05T06:08:41.243+0000] {taskinstance.py:3482} INFO - 0 downstream tasks scheduled from follow-on schedule check
[2024-07-05T06:08:41.244+0000] {local_task_job_runner.py:222} INFO - ::endgroup::
